version: '3.8'

services:
  lama:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 8g
    volumes:
      - ../domains:/root/data
